-- Active: 1706929329353@@127.0.0.1@3306

### Recuperar todas las peliculas
GET http://localhost:1234/movies

### Recuperar peliculas por el Genero
GET http://localhost:1234/movies?genre=Drama

### Recuperar pelicula por el id
GET http://localhost:1234/movies/304dd306-c2c4-11ee-9029-0242ac120002

### Crear una pelicula
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "Star Wars",
    "year": 1977,
    "director": "George Lucas",
    "duration": 121,
    "poster": "https://m.media-amazon.com/images/I/91obuWzA3XL._AC_UF1000,1000_QL80_.jpg",
    "genre": ["Action", "Adventure", "Sci-Fi"]
}

### Actualizar solo una parte de la pelicula

PATCH http://localhost:1234/movies/550ea104-c265-11ee-b14b-0242ac120002
Content-Type: application/json

{
    "year": 1961,
    "duration":170
}


### peticion de tipo Delete
DELETE http://localhost:1234/movies/702295eb-c2c4-11ee-9029-0242ac120002