
### Recuperar todas las peliculas
GET http://localhost:1234/movies

### Recuperar peliculas por el Genero
GET http://localhost:1234/movies?genre=Action

### Recuperar pelicula por el id
GET http://localhost:1234/movies/5ad1a235-0d9c-410a-b32b-220d91689a08

### Crear una pelicula
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "Star Wars",
    "year": 1977,
    "director": "George Lucas",
    "duration": 121,
    "poster": "https://m.media-amazon.com/images/I/91obuWzA3XL._AC_UF1000,1000_QL80_.jpg",
    "genre": ["Action", "Adventure", "Sci-Fi"]
}

### Actualizar solo una parte de la pelicula

PATCH http://localhost:1234/movies/5ad1a235-0d9c-410a-b32b-220d91689a08
Content-Type: application/json

{
    "year": 1965,
    "duration":170
}


### peticion de tipo Delete
DELETE http://localhost:1234/movies/c8a7d63f-3b04-44d3-9d95-8782fd7dcfaf